OFFENSIVE_COLUMNS_LIST = [
    "player",
    "Tm",
    "Cmp",
    "Att",
    "Yds",
    "TD",
    "Int",
    "Sk",
    "Yds.1",
    "Lng",
    "Rate",
    "Att.1",
    "Yds.2",
    "TD.1",
    "Lng.1",
    "Tgt",
    "Rec",
    "Yds.3",
    "TD.2",
    "Lng.2",
    "Fmb",
    "FL",
    "player_id",
]

OFFENSIVE_RENAMING_DICT = rename_dict = {
    "player": "player",
    "Tm": "team",
    "Cmp": "pass_cmp",
    "Att": "pass_att",
    "Yds": "pass_yds",
    "TD": "pass_td",
    "Int": "pass_int",
    "Sk": "pass_sacked",
    "Yds.1": "pass_sacked_yds",
    "Lng": "pass_long",
    "Rate": "pass_rating",
    "Att.1": "rush_att",
    "Yds.2": "rush_yds",
    "TD.1": "rush_td",
    "Lng.1": "rush_long",
    "Tgt": "targets",
    "Rec": "rec",
    "Yds.3": "rec_yds",
    "TD.2": "rec_td",
    "Lng.2": "rec_long",
    "Fmb": "fumbles",
    "FL": "fumbles_lost",
    "player_id": "player_id",
}


PLAYER_DEFENSE_RENAMING_DICT = {
    "Player": "player",
    "Tm": "team",
    "Int": "interceptions",
    "Yds": "interception_return_yards",
    "TD": "interception_touchdowns",
    "Lng": "longest_interception_return",
    "Sk": "sacks",
    "Comb": "total_tackles",
    "TFL": "tackles_for_loss",
    "QBHits": "qb_hits",
    "FR": "fumble_recoveries",
    "Yds.1": "fumble_return_yards",
    "TD.1": "fumble_touchdowns",
}

PUNT_KICK_RETURNS_RENAMING_DICT = {
    "Player": "player",
    "Tm": "team",
    "Yds": "kick_return_yards",
    "Yds.1": "punt_return_yards",
    "TD": "kick_return_touchdowns",
    "TD.1": "punt_return_touchdowns",
}

PUNT_KICK_RENAMING_DICT = {
    "Player": "player",
    "Tm": "team",
    "XPM": "extra_points_made",
    "XPA": "extra_points_attempted",
    "FGM": "field_goals_made",
    "FGA": "field_goals_attempted",
    "Pnt": "punts",
    "Yds": "punt_yards",
    "Y/P": "yards_per_punt",
    "Lng": "longest_punt",
}

PASSING_ADVANCED_RENAMING_DICT = {
    "Player": "player",
    "Tm": "team",
    "1D": "first_downs_thrown",
    "1D%": "passing_first_down_pct",
    "IAY": "passing_intended_air_yards",
    "IAY/PA": "passing_intended_air_yards_per_att",
    "CAY": "passing_completed_air_yards",
    "CAY/Cmp": "passing_completed_air_yards_per_cmp",
    "CAY/PA": "passing_completed_air_yards_per_att",
    "YAC": "passing_yards_after_catch",
    "YAC/Cmp": "passing_yards_after_catch_per_cmp",
    "Drops": "passing_drops",
    "Drop%": "passing_drop_pct",
    "BadTh": "bad_throws",
    "Bad%": "bad_throw_pct",
    "Sk": "sacks_taken",
    "Bltz": "blitzes_taken",
    "Hrry": "hurries_taken",
    "Hits": "qb_hits_taken",
    "Prss": "pressures_taken",
    "Prss%": "pressure_pct_taken",
    "Scrm": "scrambles",
    "Yds/Scr": "yards_per_scramble",
}

RECEIVING_ADVANCED_RENAMING_DICT = {
    "Player": "player",
    "Tm": "team",
    "1D": "receiving_first_downs",
    "YBC": "receiving_yards_before_catch",
    "YBC/R": "receiving_ybc_per_reception",
    "YAC": "receiving_yards_after_catch",
    "YAC/R": "receiving_yac_per_reception",
    "ADOT": "receiving_average_depth_of_target",
    "BrkTkl": "breceiving_roken_tackles",
    "Rec/Br": "receiving_receptions_per_broken_tackle",
    "Drop": "receiving_drops",
    "Drop%": "receiving_drop_pct",
    "Int": "receiving_interceptions",
    "Rat": "receiving_passer_rating",
}

RUSHING_ADVANCED_RENAMING_DICT = {
    "Player": "player",
    "Tm": "team",
    "1D": "rushing_first_downs",
    "YBC": "rushing_yards_before_contact",
    "YBC/Att": "rushing_ybc_per_attempt",
    "YAC": "rushing_yards_after_contact",
    "YAC/Att": "rushing_yac_per_attempt",
    "BrkTkl": "rushing_broken_tackles",
    "Att/Br": "rushing_attempts_per_broken_tackle",
}

DEFENSE_ADVANCED_RENAMING_DICT = {
    "Player": "player",
    "Tm": "team",
    "Tgt": "defense_targets",
    "Cmp": "defense_completions_allowed",
    "Cmp%": "defense_completion_pct",
    "Yds/Cmp": "defense_yards_per_completion",
    "Yds/Tgt": "defense_yards_per_target",
    "Rat": "defense_passer_rating_against",
    "DADOT": "defense_defensive_avg_depth_of_tgt",
    "Air": "defense_air_yards_allowed",
    "YAC": "defense_yac_allowed",
    "Bltz": "defense_blitzes",
    "Hrry": "defense_hurries",
    "QBKD": "defense_qb_hits",
    "Prss": "defense_pressures",
    "Comb": "defense_combined_tackles",
    "MTkl": "defense_missed_tackles",
    "MTkl%": "defense_missed_tackle_pct",
}

SNAP_COUNT_RENAMING_DICT = {
    "Player": "player",
    "Pos": "position",
    "Num": "offense_snaps",
    "Pct": "offense_pct",
    "Num.1": "defense_snaps",
    "Pct.1": "defense_pct",
    "Num.2": "special_teams_snaps",
    "Pct.2": "special_teams_pct",
}
